### PR TITLE
Update Spoofer.h

### PR DESCRIPTION
**Pull request by RutOf**
Fixed not having to restart after using the spoofer and made it up to the customer what they wanted.

### CODE REVIEW

**Comment by RutOf** [comment]
msedge_eJbTbgbxGd

**Review by Fnoberz — CHANGES_REQUESTED** [review]
```C++ 
	closesocket(s);
	decrypt(recvbuf, d);
	memcpy(out, d, strlen(d));
```

You can put this in your replacement.

**Review by Fnoberz — COMMENTED** [review]
And including corrections in the retrospective review as well.

**Review by RutOf — COMMENTED** [review]
correct mistake Some things and some things can't be checked, for example, cmd is disabled by itself. without asking the owner

**Comment by Fnoberz** [comment]
@RutOf Alright

<table>
<tr>
	<td> Fixed
	<td> Removed
</table>

**Review by Fnoberz — COMMENTED** [review]
Niced !

**Pull request merged**
